-- ============================================
-- DESIGN GUARDIAN - STORAGE (OBSOLÈTE)
-- ============================================
-- ⚠️ Ce fichier configurait le bucket `svg-files` de l'ANCIENNE version SaaS
-- (upload de fichiers SVG), abandonnée lors du pivot vers le plugin Figma (mars 2026).
--
-- Le bucket ACTIF est `snapshots` (snapshots JSON + rendus `*_render.json`),
-- créé et policé par `migrations/008_snapshot_storage.sql`.
--
-- Le bucket `svg-files` ne contient que des SVG de test pré-plugin (données mortes)
-- et peut être supprimé du projet Supabase.
-- ============================================
