import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { getSupabaseClient } from '../config/supabase.js';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { createProjectSchema } from '../types/api.js';
import type { ProjectResponse, ProjectsListResponse, ErrorResponse } from '../types/api.js';
import type { AppEnv } from '../types/hono.js';

const projectsRouter = new Hono<AppEnv>();

projectsRouter.get('/', authMiddleware, async (c) => {
  const { data, error } = await getSupabaseClient()
    .from('projects')
    .select('*')
    .eq('owner_id', c.get('userId'))
    .order('created_at', { ascending: false });

  if (error) return c.json<ErrorResponse>({ error: 'Failed to fetch projects', details: error.message }, 500);
  return c.json<ProjectsListResponse>({ projects: data });
});

projectsRouter.get('/:id', authMiddleware, async (c) => {
  const { data, error } = await getSupabaseClient()
    .from('projects').select('*').eq('id', c.req.param('id')).single();

  if (error || !data) return c.json<ErrorResponse>({ error: 'Project not found' }, 404);
  return c.json<ProjectResponse>({ project: data });
});

projectsRouter.post('/', authMiddleware, zValidator('json', createProjectSchema), async (c) => {
  const body = c.req.valid('json');
  const { data, error } = await getSupabaseClient()
    .from('projects')
    .insert({
      name: body.name,
      description: body.description ?? null,
      owner_id: c.get('userId'),
      // api_key is auto-generated by DB default (gen_random_uuid())
    })
    .select()
    .single();

  if (error || !data) return c.json<ErrorResponse>({ error: 'Failed to create project', details: error?.message }, 500);
  return c.json<ProjectResponse>({ project: data }, 201);
});

projectsRouter.delete('/:id', authMiddleware, async (c) => {
  const { error } = await getSupabaseClient()
    .from('projects')
    .delete()
    .eq('id', c.req.param('id'))
    .eq('owner_id', c.get('userId'));

  if (error) return c.json<ErrorResponse>({ error: 'Failed to delete project', details: error.message }, 500);
  return c.json<{ message: string }>({ message: 'Project deleted' });
});

export { projectsRouter };
