import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { getSupabaseClient } from '../config/supabase.js';
import { authMiddleware } from '../middleware/auth.middleware.js';
import { createProjectSchema, autoInitSchema } from '../types/api.js';
import type { ProjectResponse, ProjectsListResponse, AutoInitResponse, ErrorResponse } from '../types/api.js';
import type { AppEnv } from '../types/hono.js';

const projectsRouter = new Hono<AppEnv>();

// Simple in-memory rate limiter: max 10 auto-init calls per IP per minute.
const _autoInitBucket = new Map<string, { n: number; resetAt: number }>();
function _checkAutoInitRate(ip: string): boolean {
  const now = Date.now();
  const b = _autoInitBucket.get(ip);
  if (!b || b.resetAt < now) { _autoInitBucket.set(ip, { n: 1, resetAt: now + 60_000 }); return true; }
  if (b.n >= 10) return false;
  b.n++;
  return true;
}

// ── Auto-init (no auth — Figma file key is the identifier) ───────────────────
projectsRouter.post('/auto-init', zValidator('json', autoInitSchema), async (c) => {
  const ip = c.req.header('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';
  if (!_checkAutoInitRate(ip)) return c.json<ErrorResponse>({ error: 'Too many requests' }, 429);
  const { figma_file_key, figma_file_name } = c.req.valid('json');
  const db = getSupabaseClient();

  const { data: existing } = await db
    .from('projects')
    .select('id, name, plan, api_key')
    .eq('figma_file_key', figma_file_key)
    .maybeSingle();

  if (existing) {
    return c.json<AutoInitResponse>({
      api_key: existing.api_key,
      project: { id: existing.id, name: existing.name, plan: existing.plan },
    });
  }

  const { data: created, error } = await db
    .from('projects')
    .insert({ figma_file_key, name: figma_file_name })
    .select('id, name, plan, api_key')
    .single();

  if (error || !created) return c.json<ErrorResponse>({ error: 'Failed to create project', details: error?.message }, 500);
  return c.json<AutoInitResponse>({
    api_key: created.api_key,
    project: { id: created.id, name: created.name, plan: created.plan },
  }, 201);
});

projectsRouter.get('/', authMiddleware, async (c) => {
  const { data, error } = await getSupabaseClient()
    .from('projects')
    .select('*')
    .eq('owner_id', c.get('userId'))
    .order('created_at', { ascending: false });

  if (error) return c.json<ErrorResponse>({ error: 'Failed to fetch projects', details: error.message }, 500);
  return c.json<ProjectsListResponse>({ projects: data });
});

projectsRouter.get('/:id', authMiddleware, async (c) => {
  const { data, error } = await getSupabaseClient()
    .from('projects').select('*').eq('id', c.req.param('id')).single();

  if (error || !data) return c.json<ErrorResponse>({ error: 'Project not found' }, 404);
  return c.json<ProjectResponse>({ project: data });
});

projectsRouter.post('/', authMiddleware, zValidator('json', createProjectSchema), async (c) => {
  const body = c.req.valid('json');
  const { data, error } = await getSupabaseClient()
    .from('projects')
    .insert({
      name: body.name,
      description: body.description ?? null,
      owner_id: c.get('userId'),
      // api_key is auto-generated by DB default (gen_random_uuid())
    })
    .select()
    .single();

  if (error || !data) return c.json<ErrorResponse>({ error: 'Failed to create project', details: error?.message }, 500);
  return c.json<ProjectResponse>({ project: data }, 201);
});

projectsRouter.delete('/:id', authMiddleware, async (c) => {
  const { error } = await getSupabaseClient()
    .from('projects')
    .delete()
    .eq('id', c.req.param('id'))
    .eq('owner_id', c.get('userId'));

  if (error) return c.json<ErrorResponse>({ error: 'Failed to delete project', details: error.message }, 500);
  return c.json<{ message: string }>({ message: 'Project deleted' });
});

export { projectsRouter };
